@echo off
rem OpenFlow build script for the desktop build machine.
rem Run from the repo root: scripts\build-on-desktop.cmd [check|build]

setlocal
set "PATH=%USERPROFILE%\.cargo\bin;%PATH%"
set "MODE=%~1"
if "%MODE%"=="" set "MODE=check"

rem Updater artifacts are signed with the key generated by `tauri signer
rem generate`. It lives outside the repo and never goes into git. Without it
rem the build still succeeds but produces no .sig, and published updates would
rem be rejected by every installed copy.
rem The variable takes the key itself or a path to it; the CLI accepts both,
rem and there is no *_PATH variant (a build with only a public key configured
rem fails outright rather than shipping unsigned artifacts).
set "TAURI_SIGNING_PRIVATE_KEY=%USERPROFILE%\.tauri\openflow_updater.key"
rem The key has no password. cmd cannot hold an empty variable (`set "X="`
rem deletes it), so the CLI would stop and prompt for one — which hangs a build
rem started over SSH forever. CI mode makes it take the empty default instead.
set "CI=true"
if not exist "%TAURI_SIGNING_PRIVATE_KEY%" (
    echo ERROR: no updater signing key at %TAURI_SIGNING_PRIVATE_KEY%
    echo        restore it from backup, the build cannot sign updates without it
    exit /b 1
)

cd /d "%~dp0\..\apps\desktop"

if not exist node_modules (
    echo === npm install ===
    call npm install --no-audit --no-fund || exit /b 1
)

echo === frontend build ===
call npm run build || exit /b 1

cd src-tauri

if "%MODE%"=="check" (
    echo === cargo check ===
    cargo check 2>&1
    exit /b %ERRORLEVEL%
)

echo === tauri build ===
cd ..
call npx tauri build --ci || exit /b 1
echo BUILD_DONE
